promtion_ids:
- "4294098" # 新手任務獎勵
- "4294099" # 關懷救援金
- "4217101" # App download
- "4021089" # 升級獎勵
- "4271118" # 幸運抽獎
- "4023093" # 筆筆存送
- "4023094" # 首存
- "4023095" # 二存
- "4244096" # 三存
- "4023097" # 四存
- "4023098" # 五存
- "4023099" # 累計存款
- "4023100" # 存款達標
- "4023101" # 手動活動紅利
- "4023102" # 手工報名活動
- "4272097" # 比賽排行榜
- "4236123" # 哩程碑
- "4272092" # 排行榜＋哩程碑

promotion_id: 
- "4674108" # 新手任務獎勵
- "4658094" 
- "4663097"
- "4654112"
- "4654112"
- "4654112"

promtion_id_lodibet:
- "4294098" # 新手任務獎勵
- "4294099" # 關懷救援金
- "4217101" # App download
- "4021089" # 升級獎勵
- "4271118" # 幸運抽獎
- "4023093" # 筆筆存送
- "4023094" # 首存
- "4023095" # 二存
- "4244096" # 三存
- "4023097" # 四存
- "4023098" # 五存
- "4023099" # 累計存款
- "4023100" # 存款達標
- "4023101" # 手動活動紅利
- "4023102" # 手工報名活動
- "4272097" # 比賽排行榜
- "4236123" # 哩程碑
- "4272092" # 排行榜＋哩程碑

promtion_ids_tcgdemov3:
- "4225097" # 新手任務獎勵
- "4225089" # 註冊獎勵
- "4225096" # App download
- "4228089" # 升級獎勵
- "4235092" # 幸運抽獎
- "4227101" # 手動活動紅利
- "4228091" # 手工報名活動

promotion_ids_for_deposit_2:
- "4200126" # 首存
- "4200127" # 二存
- "4200128" # 三存
- "4200129" # 四存
- "4200130" # 五存
- "4200125" # 筆筆存送


promtions_name:
- "carrine mission+milestone"  # 排行榜＋哩程碑
- "carrine milestone" # 哩程碑
- "carrine mission" #比賽排行榜
- "carrine 手工報名" # 手工報名活動
- "carrine 手動活動紅利"  # 手動活動紅利
- "carrine 存款達標"  # 存款達標
- "carrine 累計存款"  # 累計存款
- "carrine fifth deposit"  # 五存
- "carrine fourth deposit"  # 四存
- "carrine third deposit"  # 三存
- "carine second deposit"  # 二存
- "carrine first deposit"  # 首存
- "carrine 筆筆"  # 筆筆存送
- "carrine lucky"  # 幸運抽獎
- "tcg-108181 upgrade test"  # 升級獎勵
- "carrine app download"  # App download
- "carrine 關懷援助金"  # 關懷救援金
- "carrine 註冊獎勵"  # 註冊獎勵
- "carrine test"  # 新手任務獎勵

ticket_id_gi8viet:
- "1531014" # cash
- "1531015" # raffle
- "1531018" # egg
- "1531019" # wheel
- "1531021" # 商品
- "1533015" # free spin
- "1531023" # 拼多多
- "1530019" # 充值折抵

ticket_id_gi8viet_expire:
- "1250016" # cash
- "1250014" # raffle
- "1250015" # egg
- "1241021" # wheel
- "1250017" # 商品
- "1216020" # free spin
- "1230017" # 拼多多

ticket_id_huamei:
- "1216015" # cash
- "1200049" # raffle
- "1200050" # egg
- "1201014" # wheel
- "1202015" # 商品
- "1150027" # free spin
- "1200054" # 拼多多

ticket_id_tcgdemov3:
- "1209039" # cash
- "1185014" # raffle
- "1151014" # egg
- "1210014" # wheel
- "1202015" # 商品
- "1210023" # free spin
- "1200054" # 拼多多


ticket_id_rollbet:
- "1217016" # cash
- "1217015" # raffle
- "1217014" # egg
- "1217017" # wheel
- "1217018" # 商品
- "1150027" # free spin #目前沒方案
- "1217020" # 拼多多

ticket_id_lodibet:
- "1217023" # cash
- "1217024" # raffle
- "1217025" # egg
- "1217026" # wheel
- "1217027" # 商品
- "1210023" # free spin #目前沒方案
- "1217022" # 拼多多



testing_account1:   #暫時換掉
  - "bnm111"
  - "bnm222"
  - "bnm985"
  - "bnm300"
  - "bnm301"
  - "bnm302"
  - "bnm303"
  - "bnm304"
  - "carrine008"
  - "ppp111"
  - "bnm984"
  - "bdd901"
  - "five001"
  - "five002"
  - "mon001"
  - "five009"
  - "feb001"
  - "feb002"
  - "feb006"
  - "bnm555"
  - "bnm888"
  - "bnm333"
  - "bnm111"
  - "bnm222"
  - "bnm985"
  - "bnm300"
  - "bnm301"
  - "bnm302"
  - "bnm303"
  - "bnm304"
  - "carrine008"
  - "ppp111"
  - "bnm984"
  - "bdd901"
  - "five001"
  - "five002"
  - "mon001"
  - "five009"
  - "feb001"
  - "feb002"
  - "feb006"
  - "bnm555"
  - "bnm888"
  - "bnm333"
  - "bnm302"
  - "bnm303"
  - "bnm304"
  - "carrine008"
  - "ppp111"
  - "bnm984"
  - "bdd901"
  - "five001"
  - "five002"
  - "mon001"
  - "five009"
  - "feb001"
  - "feb002"
  - "feb006"
  - "bnm555"
  - "bnm888"
  - "bnm333"
  


testing_account:
- "bnm908"

promotion:
- "carrine 手工報名"
promotion_id:
- "4023102"



VIP_testing_account:
- "pop111" 
- "pop999"
- "pop333" 
- "pop555" 


first_testing_account:
  carrine008:
    first_expect_rank: 4  
    second_expect_rank: 2  
  five001:
    first_expect_rank: 3 
    second_expect_rank: 4
  kirin350:
    first_expect_rank: 2  
    second_expect_rank: 3
  kkk999:
    first_expect_rank: 1 
    second_expect_rank: 1


bet_amount_list:
- "10"
- "50"
- "100"
- "500"

second_bet_amount_list:
- "200"
- "50"
- "100"
- "600"